sudo: false
language: php

php:
  - 5.6
  - 7.0

matrix:
  fast_finish: true
    
before_install:
  - /home/travis/.phpenv/versions/$(phpenv version-name)/bin/composer self-update
    
before_script:
  - composer install
  
script: 
  - bin/phpunit --coverage-text
 
